name: linuxstats
version: 1.1.6
summary: LinuxStats
description: A flutter application to monitor your Linux PC statistic.

confinement: strict
base: core18
grade: stable

apps:
  linuxstats:
    command: flutter_linuxstats
    extensions: [flutter-dev]

parts:
  linuxstats:
    plugin: flutter
    source: https://github.com/Malte2036/flutter_linuxstats.git
    flutter-target: lib/main.dart

